// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY0mf6UA_yXDwbu_day2VaNoghydOMExE',
    appId: '1:729694504381:web:5fbd04b682199866b5bed4',
    messagingSenderId: '729694504381',
    projectId: 'new-utibu-health-app',
    authDomain: 'new-utibu-health-app.firebaseapp.com',
    storageBucket: 'new-utibu-health-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF76GSCb5GPgVMK-U6OvEXiInnJHZlNJs',
    appId: '1:729694504381:android:990458e7d3580df1b5bed4',
    messagingSenderId: '729694504381',
    projectId: 'new-utibu-health-app',
    storageBucket: 'new-utibu-health-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAksaZUvQgw9FgTND4N1s-BFcLhHs-kCq0',
    appId: '1:729694504381:ios:45918b2c38e4f773b5bed4',
    messagingSenderId: '729694504381',
    projectId: 'new-utibu-health-app',
    storageBucket: 'new-utibu-health-app.appspot.com',
    iosBundleId: 'com.example.newUtibuHealthApp',
  );
}
